### ISSUE TITLE
UAV has Helicopter icon

### ISSUE THREAD

**Issue by theYoursTruly** [alexcroox/R3-Web#2]
UAV (Darter) has chopper icon instead of drone one.

Read from DB:
```sql
[{
"unit": "B Alpha 4-1:1",
"id": "",
"pos": [4422.78,2398.15,1001.16],
"dir": 0,
"cls": "B_UAV_01_F",
"ico": "iconHelicopter",
"icp": "Map_UAV_01_CA",
"fac": "1",
"grp": "Alpha 4-1",
"crw": [],
"cgo": []
}]
```

**Comment by alexcroox** [comment]
I've moved all map icons to Amazon S3 along side the terrain tiles to simplify updating/adding to them. 

I also built a system for auto icon colouring and resizing similar to https://titanmods.xyz/r3/tiler/ so I can add new/missing icons faster in the future that auto benefit all R3 installs because of the remote Amazon S3 usage.

The UAV icon has been used to test this new automated system and a test mission can be viewed here: https://titanmods.xyz/r3/ark/355?force

Edit: It looks like the new images I've put through the icon automator have come out double size, I'll correct that when I've had some sleep :P

**Comment by BryanBoru** [comment]
[fnc_trackVehicles.sqf](https://github.com/alexcroox/R3/blob/2d1e89e501cdee7a9dee45e2ef653c573882e009/addons/main/functions/fnc_trackVehicles.sqf#L43-L85)  
Not seeing  `vehicleClass="Autonomous";`

nor anything like `icon="\A3\Drones_F\Air_F_Gamma\UAV_01\Data\UI\Map_UAV_01_CA.paa"` in [assets-src/images/map/markers/vehicles](https://github.com/alexcroox/R3-Web/tree/master/assets-src/images/map/markers/vehicles)

**Comment by alexcroox** [comment]
The UAVs were already being tracked OK but they had no icon so they fell back to their base class of helicopter.

You won't find anything in that path now as mentioned above all vehicle icons have been moved to S3 to simplify the constant cat and mouse game of adding new icons as they are found missing or new mods released. You can find that icon here: 

https://r3icons.titanmods.xyz/Map_UAV_01_CA-east.png
![https://r3icons.titanmods.xyz/Map_UAV_01_CA-east.png](https://r3icons.titanmods.xyz/Map_UAV_01_CA-east.png)

https://r3icons.titanmods.xyz/Map_UAV_01_CA-west.png
![https://r3icons.titanmods.xyz/Map_UAV_01_CA-west.png](https://r3icons.titanmods.xyz/Map_UAV_01_CA-west.png)

https://r3icons.titanmods.xyz/Map_UAV_01_CA-independant.png
![https://r3icons.titanmods.xyz/Map_UAV_01_CA-independant.png](https://r3icons.titanmods.xyz/Map_UAV_01_CA-independant.png)

https://r3icons.titanmods.xyz/Map_UAV_01_CA-civilian.png
![https://r3icons.titanmods.xyz/Map_UAV_01_CA-civilian.png](https://r3icons.titanmods.xyz/Map_UAV_01_CA-civilian.png)

With example playback using it: https://titanmods.xyz/r3/ark/355?force

**Comment by alexcroox** [comment]
But I will welcome a PR for the correct `isKindOf` for autonomous vehicles if the fact they are logged in the data as a helicopter bothers anyone :)

**Comment by BryanBoru** [comment]
When I made my comment YoursTruly's post was the only one I saw. Very Odd. Was not meaning anything by it.

**Comment by alexcroox** [comment]
Ha no worries you must have had the page open for 2 hours in a tab!

The new vehicle icon submission tool is available here: https://titanmods.xyz/r3/tiler/icons

![https://d3vv6lp55qjaqc.cloudfront.net/items/2P1s311x2L1N3q0z1u3s/Screen%20Recording%202017-01-09%20at%2012.05%20pm.gif?X-CloudApp-Visitor-Id=220295 (188KB)](https://d3vv6lp55qjaqc.cloudfront.net/items/2P1s311x2L1N3q0z1u3s/Screen%20Recording%202017-01-09%20at%2012.05%20pm.gif?X-CloudApp-Visitor-Id=220295 (188KB))

**Comment by alexcroox** [comment]
New issue created for the addon in relation to this https://github.com/alexcroox/R3/issues/12
