### ISSUE TITLE
In progress icon missing

### ISSUE THREAD

**Issue by Arcanum417** [alexcroox/R3-Web#7]
http://i.imgur.com/S44P82c.png

**Comment by alexcroox** [comment]
Good spot thanks, I missed that icon when I moved all icon assets to AWS S3. 

The icon should be https://r3icons.titanmods.xyz/iconMan-civilian-trim.png I'll get that fixed when I'm home tomorrow night

**Comment by alexcroox** [comment]
If you don't want to wait until the next release replace `/views/templates/missions-table.php` with this file https://cl.ly/izSa/missions-table.php
